const types = {
  INTEGRATIONS : {
    KASEYA: {
      CREATE: "KASEYA-CREATE",
      UPDATE: "KASEYA-UPDATE",
      VIEW: "KASEYA-VIEW",
      FETCHING: "KASEYA-FETCHING",
      CANCELFETCHING: "KASEYA-CANCELFETCHING",
      UPDATING: "KASEYA-UPDATING"
    }
  }
}
export default types;