export const types = {
  INTEGRATIONS : {
    KASEYA: {
      CREATE: "KASEYA_CREATE",
      UPDATE: "KASEYA_UPDATE",
      VIEW: "KASEYA_VIEW",
      FETCHING: "KASEYA_FETCHING",
      CANCELFETCHING: "KASEYA_CANCELFETCHING",
      UPDATING: "KASEYA_UPDATING"
    },
    DOMAINTRACKER:{
      VIEW:"DOMAINTRACKER_VIEW",
      WHOIS:"Whois",
      A:"A"
    },
  },
  WISE_MESSAGE: {
    ADD: "ADD_WISE_MESSAGE",
    CLEAR: "CLEAR_WISE_MESSAGE",
  }
};
