const types = {
  INTEGRATIONS : {
    KASEYA: {
      CREATE: "KASEYA_CREATE",
      UPDATE: "KASEYA_UPDATE",
      VIEW: "KASEYA_VIEW",
      FETCHING: "KASEYA_FETCHING",
      CANCELFETCHING: "KASEYA_CANCELFETCHING",
      UPDATING: "KASEYA_UPDATING"
    }
  },
  ERROR_MESSAGES: {
    ADD: "ADD_ERROR_MESSAGE",
    CLEAR: "CLEAR_ERROR_MESSAGE",
  },
  SUCCESS_MESSAGES: {
    ADD: "ADD_SUCCESS_MESSAGE",
    CLEAR: "CLEAR_SUCCESS_MESSAGE",
  }
}
export default types;